# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-15 08:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RankListDailyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_date', models.DateField(db_index=True, default=datetime.date.today, verbose_name='type in date')),
                ('code', models.IntegerField(db_index=True, verbose_name='stock code')),
                ('name', models.CharField(max_length=20, verbose_name='stock name')),
                ('bamount', models.IntegerField(verbose_name='buy amount')),
                ('samount', models.IntegerField(verbose_name='sold amount')),
                ('type', models.SmallIntegerField(choices=[(0, '\u8fde\u7eed\u4e09\u4e2a\u4ea4\u6613\u65e5\u5185\uff0c\u65e5\u5747\u6362\u624b\u7387\u4e0e\u524d\u4e94\u4e2a\u4ea4\u6613\u65e5\u7684\u65e5\u5747\u6362\u624b\u7387\u7684\u6bd4\u503c\u8fbe\u523030\u500d\uff0c\u4e14\u6362\u624b\u7387\u7d2f\u8ba1\u8fbe20%\u7684\u80a1\u7968'), (1, '\u8fde\u7eed\u4e09\u4e2a\u4ea4\u6613\u65e5\u5185\uff0c\u6da8\u5e45\u504f\u79bb\u503c\u7d2f\u8ba1\u8fbe20%\u7684\u8bc1\u5238'), (2, '\u6da8\u5e45\u504f\u79bb\u503c\u8fbe7%\u7684\u8bc1\u5238'), (3, '\u65e0\u4ef7\u683c\u6da8\u8dcc\u5e45\u9650\u5236\u7684\u8bc1\u5238'), (4, '\u6362\u624b\u7387\u8fbe20%\u7684\u8bc1\u5238')], verbose_name='describe in ranklist')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ranklistdailydata',
            unique_together=set([('code', 'type_date', 'type')]),
        ),
    ]
